ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns= [
    path('add/<int:product_id>/', views.add_cart,name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.cart_remove,name='full_remove'),
]   

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
        

ecommerce/ecommerceapp/urls.py
from django.urls import path,include
from . import views

app_name='ecommerceapp'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    #path('', views.Basepoint, name='Basepoint'),
    path('<slug:c_slug>/', views.allProdCat, name= 'products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name= 'prodCatdetail'),
]

ecommerce/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns= [
    path('', views.SearchResult, name='SearchResult'),
]

ecommerce/cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id= models.CharField(max_length=250, blank=True)
    date_added= models.DateField(auto_now_add= True)

    class Meta:
        db_table='Cart'
        ordering= ['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product= models.ForeignKey(Product, on_delete= models.CASCADE)
    cart=  models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity= models.IntegerField()
    active= models.BooleanField(default= True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerce/ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name= models.CharField(max_length= 250, unique= True)
    slug= models.SlugField(max_length= 250, unique= True)
    description= models.TextField(blank= True)
    image= models.ImageField(upload_to='category', blank= True)

    class Meta:
        ordering= ('name',)
        verbose_name= 'category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerceapp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name= models.CharField(max_length= 250, unique= True)
    slug= models.SlugField(max_length= 250, unique= True)
    proddesc= models.TextField(blank= True)
    price= models.DecimalField(max_digits= 10, decimal_places= 2)
    category= models.ForeignKey(Category,on_delete=models.CASCADE)
    image= models.ImageField(upload_to='product', blank= True)
    stock= models.IntegerField()
    available= models.BooleanField(default= True)
    created= models.DateTimeField(auto_now_add= True)
    updated= models.DateTimeField(auto_now= True)

    def get_url(self):
        return reverse('ecommerceapp:prodCatdetail', args= [self.category.slug, self.slug])

    class Meta:
        ordering= ('name',)
        verbose_name= 'product'
        verbose_name_plural='products'

    def str(self):
        return '{}'.format(self.name)

ecommerce/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from ecommerceapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart= request.session.session_key
    if not cart:
        cart= request.session.create()
    return cart

def add_cart(request,product_id):
    product= Product.objects.get(id=product_id)
    try:
        cart= Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:  
        cart= Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item= CartItem.objects.get(product= product, cart= cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item= CartItem.objects.create(
            product= product,
            quantity= 1,
            cart= cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items= None):
    try:
        cart= Cart.objects.get(cart_id= _cart_id(request))
        cart_items= CartItem.objects.filter(cart= cart,active= True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items= cart_items, total= total, counter= counter))

def cart_remove(request,product_id):
    cart= Cart.objects.get(cart_id= _cart_id(request))
    product= get_object_or_404(Product,id= product_id)
    cart_item= CartItem.objects.get(product= product,cart= cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,prodct_id):
    cart= Cart.object.get(cart_id=_card_id(request))
    product= get_object_or_404(Product,id=product_id)
    cart_item= CartItem.objects.get(product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart:detail')
        

ecommerce/ecommerceapp/views.py
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def Basepoint(request):
    return HttpResponse('Hey, I am here')

def allProdCat(request, c_slug= None):
    c_page= None
    products_list= None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug= c_slug)
        products_list = Product.objects.all().filter( category= c_page, available = True )
    else:
        products_list = Product.objects.all().filter( available= True)
    paginator= Paginator(products_list, 6)
    try:
        page= int(request.GET.get('page', '1'))
    except:
        page= 1
    try:
        products= paginator.page(page)
    except (EmptyPage, InvalidPage):
        products= paginator.page(paginator.num_pages)
    
    return render(request, "category.html", { 'category':c_page, 'products': products})
    
def proDetail(request, c_slug, product_slug):
    try:
        product= Product.objects.get(category__slug= c_slug, slug= product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q
from django.http import HttpResponse
# Create your views here.

def SearchResult(request):
    # return HttpResponse('Hey, I am here')
    products= None
    query= None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products= Product.objects.all().filter(Q(name__contains= query) | Q(proddesc__contains= query))

        return render(request,"search.html",{'query':query,'products':products})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->
    <!-- <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet"> -->
    <!-- <script src="{% static 'js/popper.min.css' %}"></script> -->
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container" >
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}

{% endblock %}
</div>
{% include 'footer.html' %}

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %} 
 This is the cart page. Proceed to your items and place the order
{% endblock %}
{% block title %}
    Cart-ABC Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty 
        </h1>
        <br>
        <p class = "text-center">
            Please Click <a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">
            Your Shopping Cart 
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            Your items
                        </th>
                    </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{cart_item.product.get_absolute_url}"><img src="{{cart_item.product.image.url}}" alt= "" class="float-left rounded custom image" alt="" style="width: 1oopx;height: 100px;"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price: $ {{ cart_item.product.price }}
                        <br>
                        Qty : {{cart_item.quantity}}                         
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><ion-icon name="add-outline"></ion-icon></a><br>
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><ion-icon name="remove-outline"></ion-icon></a><br>
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><ion-icon name="trash-bin-outline"></ion-icon></a>
                    </td>
                    {% else %}
                    <td>
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><ion-icon name="remove-outline"></ion-icon></a><br>
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><ion-icon name="trash-bin-outline"></ion-icon></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>               
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please review yor shopping cart items before processing with the order payment.
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                             Total: <strong>${{total}}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
    Welcome to ABC store where you can buys different <items class=""></items>
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - ABC Store
    {% else %}
        ABC Store
    {% endif %}
{% endblock %}

{% block content %}

{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto text-center">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}">Our Product Collections</a></p>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" style="width: 100%; height: 50%">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p> 
    </div>
    {% else %}
    <div>
    <img class= "my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products">
    </div>
    <br>
    <div>
        <h1 class="text-center my-title"> Our products Collections</h1>
        <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="width: 420px; height: 520px;" href="{{product.get_url}}">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width: 100%;height: 100%;"></a>
                    <div class="card-body">
                        <h3>{{product.name}}</h3>
                        <p>${{product.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
             <div class="text-center">
               {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm" {% if products.number == pg %} active {% endif %}>{{pg}}</a>                
               {% endfor %}
             </div>
            {% endif %}
        </div>
    </div>
    <br>
</div>
{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer text-center">
    <p>&copy; ABC tech pvt ltd. All rights Reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" width="130px;" height="130px;">
    </center>
</header>

ecommerce/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ecommerceapp:allProdCat' %}">Shop</a>
          </li>
          <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><ion-icon name="cart-outline"></ion-icon>({{item_count}})</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><ion-icon name="search-outline"></ion-icon></button>
        </form>
      </div>
    </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if category %}
        {{ product.name }} - ABC Store
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx_auto">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
        </div>
        <div class="container p_image">
            <div class="row mx_auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div>
                        <img class="p_image" src="{{product.image.url}}" alt="{{product.name}}">
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p>${{product.price}}</p>
                    <p class="my_prod_title">Product Description</p>
                    <p class="text-justify my_rod_text">{{product.proddesc}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %} 
    We have variety of products.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
    {% for product in products %}
    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
        <div class="card text-center" style="width: 420px;height: 520px;" href="{{product.get_url}}">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width: 100%;height: 100%;"></a>
            <div class="card-body">
                <h3>{{product.name}}</h3>
                <p>${{product.price}}</p>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text"> 0 results found</p>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/testpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->
    <!-- <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet"> -->
    <!-- <script src="{% static 'js/popper.min.css' %}"></script> -->
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container" >
<p>Your message is {{query}}</p>
</body>
</html>